-- Supabase SQL Schema for Krushi AI Assistant

-- Enable PostGIS extension for geolocation
CREATE EXTENSION IF NOT EXISTS postgis;

-- Admins Table
CREATE TABLE admins (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    role VARCHAR(50) DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Prompt Templates Table (Versioning)
CREATE TABLE prompt_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    version VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name, version)
);

-- Villages Table (Normalized)
CREATE TABLE villages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    gps_location GEOMETRY(Point, 4326),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Farmers Table
CREATE TABLE farmers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(100),
    language_pref VARCHAR(10) DEFAULT 'en', -- en or gu
    village_id UUID REFERENCES villages(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Farmer Context (AI Memory Layer)
CREATE TABLE farmer_context (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    farmer_id UUID REFERENCES farmers(id) UNIQUE,
    crop_history JSONB DEFAULT '[]',
    recurring_issues JSONB DEFAULT '[]',
    seasonal_patterns JSONB DEFAULT '{}',
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Conversations Table
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    farmer_id UUID REFERENCES farmers(id),
    message_body TEXT NOT NULL,
    sender VARCHAR(10) NOT NULL, -- 'user' or 'ai'
    ai_structured_output JSONB, -- stores the structured JSON insight generated by the AI
    prompt_version_id UUID REFERENCES prompt_templates(id),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Crop Reports Table
CREATE TABLE crop_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    farmer_id UUID REFERENCES farmers(id),
    village_id UUID REFERENCES villages(id),
    crop_type VARCHAR(100),
    ndvi_status JSONB,
    weather_context JSONB,
    report_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_farmers_phone ON farmers(phone_number);
CREATE INDEX idx_conversations_farmer_id ON conversations(farmer_id);
CREATE INDEX idx_villages_normalized_name ON villages(normalized_name);

-- For MVP Backend Operations: Disable RLS so the FastAPI/Celery workers can insert records.
-- In production, if RLS is enabled, ensure the backend SUPABASE_KEY is the service_role key, not anon.
ALTER TABLE farmers DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE villages DISABLE ROW LEVEL SECURITY;
ALTER TABLE crop_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE farmer_context DISABLE ROW LEVEL SECURITY;
ALTER TABLE prompt_templates DISABLE ROW LEVEL SECURITY;
